services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "tpdb"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_MULTIPLE_DATABASES: users, data, parser, logging
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./postgres/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5433:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tpdb@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: