insert into public.ride_type(id, name, category, description, created_at, updated_at, created_by_id, updated_by_id)
values
    (gen_random_uuid(), 'Roller Coaster', 'Roller coaster', 'A roller coaster is a type of amusement ride that employs a form of elevated railroad track designed with tight turns, steep slopes, and sometimes inversions.', now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system')),
    (gen_random_uuid(), 'Log flume', 'WaterRide', 'A water ride is a type of amusement ride that features water, such as water slides, lazy rivers, and splash pads.', now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system')),
    (gen_random_uuid(), 'River Rapids', 'WaterRide', 'A river rapids ride is a variation of a log flume in which the water is moving at a faster pace.', now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system')),
    (gen_random_uuid(), 'Tow boat ride','WaterRide', 'A tow boat ride is a variation of a log flume in which the water is moving at a faster pace.', now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system')),
    (gen_random_uuid(), 'Dark ride', 'themed ride', 'A dark ride or ghost train is an indoor amusement ride on which passengers aboard guided vehicles travel through specially lit scenes that typically contain animation, sound, music and special effects.', now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system'));


insert into public.ride_system(id, name, description, ride_type_id, created_at, updated_at, created_by_id, updated_by_id)
VALUES
    (gen_random_uuid(), 'Omnimover', 'The Omnimover system was created by Roger E. Broggie and Bert Brundage to provide a ride system capable of providing passengers with a motion-picture-type experience by controlling the line of sight.[3] This concept also allows the designers to be able to place infrastructure elements of the attraction, such as lighting and projectors, behind the vehicles without concern for having the illusions of the attraction revealed to the riders. The system consists of a chain of vehicles operating on a track, usually hidden beneath the floor. The chain of vehicles maintains constant motion at a specific speed (usually about 2 feet or 60 centimeters per second[4]) throughout the entire course of the attraction. To facilitate boarding and disembarking from the vehicles, a conveyor belt moving at approximately the same speed as the ride vehicles parallels the track at the loading and unloading areas. Passengers step from the moving belt into the vehicle or vice versa.', (select id from ride_type where name='Dark Ride'), now(), now(), (select id from users where first_name='system'), (select id from users where first_name='system'))
