spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tpdb-data
    username: tpdb
    password: tpdb_secret
  application:
    name: 'TPDB data-service'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
#    please only use db/dummy for testing purposes
    locations:
      classpath:db/migration,classpath:db/seed,classpath:db/dummy
