spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tpdb-data
    username: tpdb
    password: tpdb_secret
  application:
    name: 'TPDB data-service'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
